### ISSUE TITLE
[RFC] Join all commands under an umbrella command `coverde`

### ISSUE THREAD

**Issue by kranfix** [mrverdant13/cov_utils#16]
The current trend in Dart CLI is to have a `a single ring to rule them all` and the currently, this project has two commands: `cov` and `x`.  
  
Why not to have a `coverde` command with the following API:  
  
```  
coverde filter  
coverde value  
coverde rm  
```  
  
If you agree, I would like to send the PR.

**Comment by mrverdant13** [comment]
Hey, @kranfix !

That was exactly the initial idea but since the `rm` command is not strictly related to coverage functionality I decided to isolate it within a "generic actions" parent command (the `x` command).

However, `rm` is currently the only command with this cov-independent behavior. Thus, I guess it's just ok to use a single parent command for now.

I'll keep an eye on new PRs in case you submit one. Otherwise, I'll be working on this change in the following days.

**Comment by mrverdant13** [comment]
If new generic commands are included in future releases, it would be handy to best them within a parent command.
Let's cross that bridge when we come to it.
